"""reset database migration

Revision ID: 61c802f6bf9e
Revises: 1d02fe2b27b8
Create Date: 2024-11-13 15:16:51.073563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c802f6bf9e'
down_revision = '1d02fe2b27b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('venmo_username', sa.String(length=64), nullable=True),
    sa.Column('cashapp_username', sa.String(length=64), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('max_stations', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=True),
    sa.Column('subscription_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['valet_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'])

    with op.batch_alter_table('station_manager', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('valet_attendant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('valet_station', schema=None) as batch_op:
        batch_op.drop_constraint('fk_valet_station_valet_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['valet_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valet_station', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_valet_station_valet_id', 'user', ['valet_id'], ['id'])

    with op.batch_alter_table('valet_attendant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('station_manager', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['valet_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['customer_id'], ['id'])

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.BLOB(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('venmo_username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('cashapp_username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('google_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subscription_id', sa.VARCHAR(length=120), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('subscription_tier', sa.VARCHAR(length=20), nullable=True),
    sa.Column('max_stations', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=1)
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
