"""Add subscription_id to User model

Revision ID: 762a9a67576b
Revises: f7d3d69986bd
Create Date: 2024-10-29 20:54:18.945137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762a9a67576b'
down_revision = 'f7d3d69986bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('stripe_customer_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('stripe_customer_id',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('subscription_id')

    # ### end Alembic commands ###
