"""Add spaces column to ValetStation

Revision ID: ba12d6796799
Revises: ecda702c8c01
Create Date: 2024-10-30 11:19:21.003103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba12d6796799'
down_revision = 'ecda702c8c01'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('valet_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spaces', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('valet_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_valet_station_valet_id',  # Add this constraint name
            'user',
            ['valet_id'],
            ['id']
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valet_station', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('valet_id')
        batch_op.drop_column('spaces')

    # ### end Alembic commands ###
