"""Add total_spaces to ValetStation

Revision ID: bb020a54cba9
Revises: ba12d6796799
Create Date: 2024-11-01 21:22:43.742312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb020a54cba9'
down_revision = 'ba12d6796799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valet_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_spaces', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valet_station', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('total_spaces')

    # ### end Alembic commands ###
