"""Add subscription tier and max stations to User model

Revision ID: ecda702c8c01
Revises: 762a9a67576b
Create Date: 2024-10-29 21:07:30.751633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecda702c8c01'
down_revision = '762a9a67576b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_tier', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('max_stations', sa.Integer(), nullable=True))
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('max_stations')
        batch_op.drop_column('subscription_tier')

    # ### end Alembic commands ###
