"""adding stripe

Revision ID: f7d3d69986bd
Revises: 7d730109b023
Create Date: 2024-10-29 19:15:32.858173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d3d69986bd'
down_revision = '7d730109b023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('subscription_plan')

    # ### end Alembic commands ###
